"""全局配置常量"""
from pathlib import Path

SUPPORTED_FORMATS = {".jpg", ".jpeg", ".png", ".webp", ".heic"}
THUMBNAIL_SIZE = (256, 256)
PREVIEW_SIZE = (512, 512)
CACHE_DIR = Path.home() / ".shiying" / "cache"
LOG_DIR = Path.home() / ".shiying" / "logs"
SHARPNESS_WEIGHT = 0.6
COMPOSITION_WEIGHT = 0.4
AI_DEFAULT_TIMEOUT = 10
AI_BATCH_SIZE = 10
AI_BATCH_DELAY = 0.05
MAX_IMAGES_PER_DIR = 5000
MAX_CACHE_SIZE_MB = 500
THUMBNAIL_LOAD_BATCH = 20
COLOR_PRIMARY = "#7C4DFF"
COLOR_SECONDARY = "#B388FF"
COLOR_BACKGROUND = "#F8F9FE"
COLOR_BORDER = "#E8E0F0"
COLOR_TEXT = "#2D2D3F"
COLOR_SCORE_HIGH = "#FFD700"
DEFAULT_COMPRESS_QUALITY = 80
COMPRESS_MIN_QUALITY = 10
COMPRESS_MAX_QUALITY = 95
