"""全局配置常量"""
from pathlib import Path

SUPPORTED_FORMATS = {".jpg", ".jpeg", ".png", ".webp", ".heic"}
THUMBNAIL_SIZE = (256, 256)
PREVIEW_SIZE = (512, 512)
CACHE_DIR = Path.home() / ".shiying" / "cache"
SHARPNESS_WEIGHT = 0.6
COMPOSITION_WEIGHT = 0.4
AI_DEFAULT_TIMEOUT = 10
AI_BATCH_SIZE = 10
AI_BATCH_DELAY = 0.05
MAX_IMAGES_PER_DIR = 5000
MAX_CACHE_SIZE_MB = 500
THUMBNAIL_LOAD_BATCH = 20
COLOR_PRIMARY = "#F8E8EE"
COLOR_SECONDARY = "#E8D5E3"
COLOR_BACKGROUND = "#FFFFFF"
COLOR_BORDER = "#E0E0E0"
COLOR_TEXT = "#333333"
COLOR_SCORE_HIGH = "#FFD700"
